[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bonding_curve_program = "GQQQNJZdqKnFwB6di7u2PnsJZLX7hzaYW4g4b5BeQ3nE"

[programs.devnet]
bonding_curve_program = "GQQQNJZdqKnFwB6di7u2PnsJZLX7hzaYW4g4b5BeQ3nE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../wallets/creator.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
